spring:
  jwt:
    secretKey: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa


  h2:
    console:
      enabled: true


  datasource:
    url: jdbc:h2:mem:db;MODE=MYSQL;
    username: sa
    password:

  thymeleaf:
    cache: false

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: create
